package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Atendimento generated by hbm2java
 */
public class Atendimento  implements java.io.Serializable {


     private Integer id;
     private Protocolo protocolo;
     private Servidor servidor;
     private String motivo;
     private String descricao;
     private Date data;
     private String situtacao;

    public Atendimento() {
    }

    public Atendimento(Protocolo protocolo, Servidor servidor, String motivo, String descricao, Date data, String situtacao) {
       this.protocolo = protocolo;
       this.servidor = servidor;
       this.motivo = motivo;
       this.descricao = descricao;
       this.data = data;
       this.situtacao = situtacao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Protocolo getProtocolo() {
        return this.protocolo;
    }
    
    public void setProtocolo(Protocolo protocolo) {
        this.protocolo = protocolo;
    }
    public Servidor getServidor() {
        return this.servidor;
    }
    
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getSitutacao() {
        return this.situtacao;
    }
    
    public void setSitutacao(String situtacao) {
        this.situtacao = situtacao;
    }




}


