package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String nome;
     private String nomeCursoDiploma;
     private String nivel;
     private String grau;
     private Short duracao;
     private Short duracaoMax;
     private Character autorizado;
     private Character reconhecido;
     private byte[] docAutorizado;
     private byte[] docReconhecido;
     private Character conceitoMec;
     private String coordenador;
     private Short cargaHoraria;
     private Short horasAc;
     private Short horasFtp;
     private Short horasIch;
     private Short horasPa;
     private Short horasOpt;
     private String tipoPeriodoLetivo;
     private String situacao;
     private Set estudantes = new HashSet(0);

    public Curso() {
    }

    public Curso(String codigo, String nome, String nomeCursoDiploma, String nivel, String grau, Short duracao, Short duracaoMax, Character autorizado, Character reconhecido, byte[] docAutorizado, byte[] docReconhecido, Character conceitoMec, String coordenador, Short cargaHoraria, Short horasAc, Short horasFtp, Short horasIch, Short horasPa, Short horasOpt, String tipoPeriodoLetivo, String situacao, Set estudantes) {
       this.codigo = codigo;
       this.nome = nome;
       this.nomeCursoDiploma = nomeCursoDiploma;
       this.nivel = nivel;
       this.grau = grau;
       this.duracao = duracao;
       this.duracaoMax = duracaoMax;
       this.autorizado = autorizado;
       this.reconhecido = reconhecido;
       this.docAutorizado = docAutorizado;
       this.docReconhecido = docReconhecido;
       this.conceitoMec = conceitoMec;
       this.coordenador = coordenador;
       this.cargaHoraria = cargaHoraria;
       this.horasAc = horasAc;
       this.horasFtp = horasFtp;
       this.horasIch = horasIch;
       this.horasPa = horasPa;
       this.horasOpt = horasOpt;
       this.tipoPeriodoLetivo = tipoPeriodoLetivo;
       this.situacao = situacao;
       this.estudantes = estudantes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getNomeCursoDiploma() {
        return this.nomeCursoDiploma;
    }
    
    public void setNomeCursoDiploma(String nomeCursoDiploma) {
        this.nomeCursoDiploma = nomeCursoDiploma;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public String getGrau() {
        return this.grau;
    }
    
    public void setGrau(String grau) {
        this.grau = grau;
    }
    public Short getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(Short duracao) {
        this.duracao = duracao;
    }
    public Short getDuracaoMax() {
        return this.duracaoMax;
    }
    
    public void setDuracaoMax(Short duracaoMax) {
        this.duracaoMax = duracaoMax;
    }
    public Character getAutorizado() {
        return this.autorizado;
    }
    
    public void setAutorizado(Character autorizado) {
        this.autorizado = autorizado;
    }
    public Character getReconhecido() {
        return this.reconhecido;
    }
    
    public void setReconhecido(Character reconhecido) {
        this.reconhecido = reconhecido;
    }
    public byte[] getDocAutorizado() {
        return this.docAutorizado;
    }
    
    public void setDocAutorizado(byte[] docAutorizado) {
        this.docAutorizado = docAutorizado;
    }
    public byte[] getDocReconhecido() {
        return this.docReconhecido;
    }
    
    public void setDocReconhecido(byte[] docReconhecido) {
        this.docReconhecido = docReconhecido;
    }
    public Character getConceitoMec() {
        return this.conceitoMec;
    }
    
    public void setConceitoMec(Character conceitoMec) {
        this.conceitoMec = conceitoMec;
    }
    public String getCoordenador() {
        return this.coordenador;
    }
    
    public void setCoordenador(String coordenador) {
        this.coordenador = coordenador;
    }
    public Short getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(Short cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public Short getHorasAc() {
        return this.horasAc;
    }
    
    public void setHorasAc(Short horasAc) {
        this.horasAc = horasAc;
    }
    public Short getHorasFtp() {
        return this.horasFtp;
    }
    
    public void setHorasFtp(Short horasFtp) {
        this.horasFtp = horasFtp;
    }
    public Short getHorasIch() {
        return this.horasIch;
    }
    
    public void setHorasIch(Short horasIch) {
        this.horasIch = horasIch;
    }
    public Short getHorasPa() {
        return this.horasPa;
    }
    
    public void setHorasPa(Short horasPa) {
        this.horasPa = horasPa;
    }
    public Short getHorasOpt() {
        return this.horasOpt;
    }
    
    public void setHorasOpt(Short horasOpt) {
        this.horasOpt = horasOpt;
    }
    public String getTipoPeriodoLetivo() {
        return this.tipoPeriodoLetivo;
    }
    
    public void setTipoPeriodoLetivo(String tipoPeriodoLetivo) {
        this.tipoPeriodoLetivo = tipoPeriodoLetivo;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public Set getEstudantes() {
        return this.estudantes;
    }
    
    public void setEstudantes(Set estudantes) {
        this.estudantes = estudantes;
    }




}


