package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Estudante generated by hbm2java
 */
public class Estudante  implements java.io.Serializable {


     private Integer id;
     private Pessoa pessoa;
     private Curso curso;
     private String matricula;
     private Short periodo;
     private String situacao;
     private String tipoVestibular;
     private Integer notaVestibular;
     private Date dataIngresso;
     private Date dataEgresso;
     private String observacao;

    public Estudante() {
    }

    public Estudante(Pessoa pessoa, Curso curso, String matricula, Short periodo, String situacao, String tipoVestibular, Integer notaVestibular, Date dataIngresso, Date dataEgresso, String observacao) {
       this.pessoa = pessoa;
       this.curso = curso;
       this.matricula = matricula;
       this.periodo = periodo;
       this.situacao = situacao;
       this.tipoVestibular = tipoVestibular;
       this.notaVestibular = notaVestibular;
       this.dataIngresso = dataIngresso;
       this.dataEgresso = dataEgresso;
       this.observacao = observacao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Short getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Short periodo) {
        this.periodo = periodo;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public String getTipoVestibular() {
        return this.tipoVestibular;
    }
    
    public void setTipoVestibular(String tipoVestibular) {
        this.tipoVestibular = tipoVestibular;
    }
    public Integer getNotaVestibular() {
        return this.notaVestibular;
    }
    
    public void setNotaVestibular(Integer notaVestibular) {
        this.notaVestibular = notaVestibular;
    }
    public Date getDataIngresso() {
        return this.dataIngresso;
    }
    
    public void setDataIngresso(Date dataIngresso) {
        this.dataIngresso = dataIngresso;
    }
    public Date getDataEgresso() {
        return this.dataEgresso;
    }
    
    public void setDataEgresso(Date dataEgresso) {
        this.dataEgresso = dataEgresso;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }




}


