package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Grupos generated by hbm2java
 */
public class Grupos  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private Set loginGrupos = new HashSet(0);

    public Grupos() {
    }

    public Grupos(String descricao, Set loginGrupos) {
       this.descricao = descricao;
       this.loginGrupos = loginGrupos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getLoginGrupos() {
        return this.loginGrupos;
    }
    
    public void setLoginGrupos(Set loginGrupos) {
        this.loginGrupos = loginGrupos;
    }




}


