package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA



/**
 * LoginGrupo generated by hbm2java
 */
public class LoginGrupo  implements java.io.Serializable {


     private Integer id;
     private Login login;
     private Grupos grupos;
     private String privilegio;

    public LoginGrupo() {
    }

    public LoginGrupo(Login login, Grupos grupos, String privilegio) {
       this.login = login;
       this.grupos = grupos;
       this.privilegio = privilegio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public Grupos getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Grupos grupos) {
        this.grupos = grupos;
    }
    public String getPrivilegio() {
        return this.privilegio;
    }
    
    public void setPrivilegio(String privilegio) {
        this.privilegio = privilegio;
    }




}


