package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer id;
     private Pessoa pessoa;
     private String senha;
     private Date ultimoacesso;
     private Set loginGrupos = new HashSet(0);

    public Login() {
    }

    public Login(Pessoa pessoa, String senha, Date ultimoacesso, Set loginGrupos) {
       this.pessoa = pessoa;
       this.senha = senha;
       this.ultimoacesso = ultimoacesso;
       this.loginGrupos = loginGrupos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Date getUltimoacesso() {
        return this.ultimoacesso;
    }
    
    public void setUltimoacesso(Date ultimoacesso) {
        this.ultimoacesso = ultimoacesso;
    }
    public Set getLoginGrupos() {
        return this.loginGrupos;
    }
    
    public void setLoginGrupos(Set loginGrupos) {
        this.loginGrupos = loginGrupos;
    }




}


