package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private String cpf;
     private Endereco endereco;
     private String nome;
     private String rg;
     private Date rgData;
     private String rgOrgao;
     private String rgEstado;
     private Date dataNascimento;
     private String nacionalidade;
     private String cidadeNatal;
     private String estadoNatal;
     private String estadoCivil;
     private Character sexo;
     private String filiacaoPai;
     private String filiacaoMae;
     private String email;
     private String telRes;
     private String telCel;
     private String necessidadeEspecial;
     private String vinculoInstituicao;
     private String observacao;
     private Set protocolosForCpfPaciente = new HashSet(0);
     private Set servidors = new HashSet(0);
     private Set estudantes = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set enderecos = new HashSet(0);
     private Set protocolosForCpfSolicitante = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(String cpf) {
        this.cpf = cpf;
    }
    public Pessoa(String cpf, Endereco endereco, String nome, String rg, Date rgData, String rgOrgao, String rgEstado, Date dataNascimento, String nacionalidade, String cidadeNatal, String estadoNatal, String estadoCivil, Character sexo, String filiacaoPai, String filiacaoMae, String email, String telRes, String telCel, String necessidadeEspecial, String vinculoInstituicao, String observacao, Set protocolosForCpfPaciente, Set servidors, Set estudantes, Set logins, Set enderecos, Set protocolosForCpfSolicitante) {
       this.cpf = cpf;
       this.endereco = endereco;
       this.nome = nome;
       this.rg = rg;
       this.rgData = rgData;
       this.rgOrgao = rgOrgao;
       this.rgEstado = rgEstado;
       this.dataNascimento = dataNascimento;
       this.nacionalidade = nacionalidade;
       this.cidadeNatal = cidadeNatal;
       this.estadoNatal = estadoNatal;
       this.estadoCivil = estadoCivil;
       this.sexo = sexo;
       this.filiacaoPai = filiacaoPai;
       this.filiacaoMae = filiacaoMae;
       this.email = email;
       this.telRes = telRes;
       this.telCel = telCel;
       this.necessidadeEspecial = necessidadeEspecial;
       this.vinculoInstituicao = vinculoInstituicao;
       this.observacao = observacao;
       this.protocolosForCpfPaciente = protocolosForCpfPaciente;
       this.servidors = servidors;
       this.estudantes = estudantes;
       this.logins = logins;
       this.enderecos = enderecos;
       this.protocolosForCpfSolicitante = protocolosForCpfSolicitante;
    }
   
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public Date getRgData() {
        return this.rgData;
    }
    
    public void setRgData(Date rgData) {
        this.rgData = rgData;
    }
    public String getRgOrgao() {
        return this.rgOrgao;
    }
    
    public void setRgOrgao(String rgOrgao) {
        this.rgOrgao = rgOrgao;
    }
    public String getRgEstado() {
        return this.rgEstado;
    }
    
    public void setRgEstado(String rgEstado) {
        this.rgEstado = rgEstado;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }
    public String getCidadeNatal() {
        return this.cidadeNatal;
    }
    
    public void setCidadeNatal(String cidadeNatal) {
        this.cidadeNatal = cidadeNatal;
    }
    public String getEstadoNatal() {
        return this.estadoNatal;
    }
    
    public void setEstadoNatal(String estadoNatal) {
        this.estadoNatal = estadoNatal;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getFiliacaoPai() {
        return this.filiacaoPai;
    }
    
    public void setFiliacaoPai(String filiacaoPai) {
        this.filiacaoPai = filiacaoPai;
    }
    public String getFiliacaoMae() {
        return this.filiacaoMae;
    }
    
    public void setFiliacaoMae(String filiacaoMae) {
        this.filiacaoMae = filiacaoMae;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelRes() {
        return this.telRes;
    }
    
    public void setTelRes(String telRes) {
        this.telRes = telRes;
    }
    public String getTelCel() {
        return this.telCel;
    }
    
    public void setTelCel(String telCel) {
        this.telCel = telCel;
    }
    public String getNecessidadeEspecial() {
        return this.necessidadeEspecial;
    }
    
    public void setNecessidadeEspecial(String necessidadeEspecial) {
        this.necessidadeEspecial = necessidadeEspecial;
    }
    public String getVinculoInstituicao() {
        return this.vinculoInstituicao;
    }
    
    public void setVinculoInstituicao(String vinculoInstituicao) {
        this.vinculoInstituicao = vinculoInstituicao;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Set getProtocolosForCpfPaciente() {
        return this.protocolosForCpfPaciente;
    }
    
    public void setProtocolosForCpfPaciente(Set protocolosForCpfPaciente) {
        this.protocolosForCpfPaciente = protocolosForCpfPaciente;
    }
    public Set getServidors() {
        return this.servidors;
    }
    
    public void setServidors(Set servidors) {
        this.servidors = servidors;
    }
    public Set getEstudantes() {
        return this.estudantes;
    }
    
    public void setEstudantes(Set estudantes) {
        this.estudantes = estudantes;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }
    public Set getProtocolosForCpfSolicitante() {
        return this.protocolosForCpfSolicitante;
    }
    
    public void setProtocolosForCpfSolicitante(Set protocolosForCpfSolicitante) {
        this.protocolosForCpfSolicitante = protocolosForCpfSolicitante;
    }




}


