package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA



/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private Integer id;
     private Servidor servidor;
     private String classe;
     private String nivel;

    public Professor() {
    }

    public Professor(Servidor servidor, String classe, String nivel) {
       this.servidor = servidor;
       this.classe = classe;
       this.nivel = nivel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Servidor getServidor() {
        return this.servidor;
    }
    
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }
    public String getClasse() {
        return this.classe;
    }
    
    public void setClasse(String classe) {
        this.classe = classe;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }




}


