package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ProtocoloServidor generated by hbm2java
 */
public class ProtocoloServidor  implements java.io.Serializable {


     private Integer id;
     private Protocolo protocolo;
     private Servidor servidor;
     private Date dataInicio;
     private Date dataFim;
     private String situacao;

    public ProtocoloServidor() {
    }

    public ProtocoloServidor(Protocolo protocolo, Servidor servidor, Date dataInicio, Date dataFim, String situacao) {
       this.protocolo = protocolo;
       this.servidor = servidor;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
       this.situacao = situacao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Protocolo getProtocolo() {
        return this.protocolo;
    }
    
    public void setProtocolo(Protocolo protocolo) {
        this.protocolo = protocolo;
    }
    public Servidor getServidor() {
        return this.servidor;
    }
    
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }




}


