package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Protocolo generated by hbm2java
 */
public class Protocolo  implements java.io.Serializable {


     private Integer id;
     private Servidor servidor;
     private Pessoa pessoaByCpfPaciente;
     private Pessoa pessoaByCpfSolicitante;
     private String protocolo;
     private String pacienteCiente;
     private String relatoCamara;
     private String relatoInstitucional;
     private String descricao;
     private Date dataInicioAtendimento;
     private Date dataFimAtendimento;
     private Date dataCriacao;
     private String setorEncaminhamento;
     private String situacao;
     private Set atendimentos = new HashSet(0);
     private Set protocoloServidors = new HashSet(0);

    public Protocolo() {
    }

	
    public Protocolo(Pessoa pessoaByCpfPaciente, String protocolo) {
        this.pessoaByCpfPaciente = pessoaByCpfPaciente;
        this.protocolo = protocolo;
    }
    public Protocolo(Servidor servidor, Pessoa pessoaByCpfPaciente, Pessoa pessoaByCpfSolicitante, String protocolo, String pacienteCiente, String relatoCamara, String relatoInstitucional, String descricao, Date dataCriacao, Date dataInicioAtendimento, Date dataFimAtendimento, String setorEncaminhamento, String situacao, Set atendimentos, Set protocoloServidors) {
       this.servidor = servidor;
       this.pessoaByCpfPaciente = pessoaByCpfPaciente;
       this.pessoaByCpfSolicitante = pessoaByCpfSolicitante;
       this.protocolo = protocolo;
       this.pacienteCiente = pacienteCiente;
       this.relatoCamara = relatoCamara;
       this.relatoInstitucional = relatoInstitucional;
       this.descricao = descricao;
       this.dataInicioAtendimento = dataInicioAtendimento;
       this.dataFimAtendimento = dataFimAtendimento;
       this.dataCriacao = dataCriacao;
       this.setorEncaminhamento = setorEncaminhamento;
       this.situacao = situacao;
       this.atendimentos = atendimentos;
       this.protocoloServidors = protocoloServidors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Servidor getServidor() {
        return this.servidor;
    }
    
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }
    public Pessoa getPessoaByCpfPaciente() {
        return this.pessoaByCpfPaciente;
    }
    
    public void setPessoaByCpfPaciente(Pessoa pessoaByCpfPaciente) {
        this.pessoaByCpfPaciente = pessoaByCpfPaciente;
    }
    public Pessoa getPessoaByCpfSolicitante() {
        return this.pessoaByCpfSolicitante;
    }
    
    public void setPessoaByCpfSolicitante(Pessoa pessoaByCpfSolicitante) {
        this.pessoaByCpfSolicitante = pessoaByCpfSolicitante;
    }
    public String getProtocolo() {
        return this.protocolo;
    }
    
    public void setProtocolo(String protocolo) {
        this.protocolo = protocolo;
    }
    public String getPacienteCiente() {
        return this.pacienteCiente;
    }
    
    public void setPacienteCiente(String pacienteCiente) {
        this.pacienteCiente = pacienteCiente;
    }
    public String getRelatoCamara() {
        return this.relatoCamara;
    }
    
    public void setRelatoCamara(String relatoCamara) {
        this.relatoCamara = relatoCamara;
    }
    public String getRelatoInstitucional() {
        return this.relatoInstitucional;
    }
    
    public void setRelatoInstitucional(String relatoInstitucional) {
        this.relatoInstitucional = relatoInstitucional;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataInicioAtendimento() {
        return this.dataInicioAtendimento;
    }
    
    public void setDataInicioAtendimento(Date dataInicioAtendimento) {
        this.dataInicioAtendimento = dataInicioAtendimento;
    }
    public Date getDataFimAtendimento() {
        return this.dataFimAtendimento;
    }

    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataFimAtendimento(Date dataFimAtendimento) {
        this.dataFimAtendimento = dataFimAtendimento;
    }
    public String getSetorEncaminhamento() {
        return this.setorEncaminhamento;
    }
    
    public void setSetorEncaminhamento(String setorEncaminhamento) {
        this.setorEncaminhamento = setorEncaminhamento;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public Set getAtendimentos() {
        return this.atendimentos;
    }
    
    public void setAtendimentos(Set atendimentos) {
        this.atendimentos = atendimentos;
    }
    public Set getProtocoloServidors() {
        return this.protocoloServidors;
    }
    
    public void setProtocoloServidors(Set protocoloServidors) {
        this.protocoloServidors = protocoloServidors;
    }




}


