package proa.model;
// Generated 02/06/2012 15:52:47 by Hibernate Tools 3.2.1.GA



/**
 * Tecnicoadministrativo generated by hbm2java
 */
public class Tecnicoadministrativo  implements java.io.Serializable {


     private Integer id;
     private Servidor servidor;
     private Character classe;
     private String nivel;
     private String padrao;

    public Tecnicoadministrativo() {
    }

    public Tecnicoadministrativo(Servidor servidor, Character classe, String nivel, String padrao) {
       this.servidor = servidor;
       this.classe = classe;
       this.nivel = nivel;
       this.padrao = padrao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Servidor getServidor() {
        return this.servidor;
    }
    
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }
    public Character getClasse() {
        return this.classe;
    }
    
    public void setClasse(Character classe) {
        this.classe = classe;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public String getPadrao() {
        return this.padrao;
    }
    
    public void setPadrao(String padrao) {
        this.padrao = padrao;
    }




}


